name: connections
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - conda-forge::pandas
  - conda-forge::networkx
  - pip:
    - torch
    - torch_geometric
    - node2vec
    - scikit-learn
    - matplotlib
    - fasttext
